Title: A watched pot never boils
Date: 2015-07-13
Author: Duncan Garmonsway
Summary: A mis-optimised kettle
Disqus_identifier: kettle

```{r pelican_conf, echo=FALSE}
#set this to true when ready to publish
ready_to_publish = FALSE

# hook_plot <- knit_hooks$get('plot')
# 
# knit_hooks$set(plot=function(x, options) {
#     if (!is.null(options$pelican.publish) && options$pelican.publish) {
#         x <- paste0("{filename}", x)
#     }
#     hook_plot(x, options)
# })
# opts_chunk$set(pelican.publish = ready_to_publish)
knitr::opts_chunk$set(fig.path='./figure/')

opts_chunk$set(dev = 'Cairo_svg')
opts_chunk$set(echo = FALSE, include = FALSE)
```

```{r setup, message = FALSE, warning = FALSE}
library(dplyr)
library(lubridate)
library(ggplot2)
library(scales)
options(lubridate.fasttime = TRUE)
```

```{r, fig.width = 16}
kettle <- read.csv("./data/kettle.csv", header = TRUE)
```

```{r, fig.width = 16, include = TRUE}
kettle %>%
# Remove decreasing steps
mutate(diff = c(NA, diff(Temp))) %>%
filter(diff > 0) %>%
# Start timer at first step
mutate(Time = Time - min(Time)) %>%
# Time in seconds
mutate(Time = origin + seconds(Time)) %>%
# Plot
ggplot(aes(Time, Temp)) +
geom_line() +
scale_x_datetime(name = "Minutes", labels = date_format("%M:%S")) +
scale_y_continuous(name = "Degrees Celsius")
```
